### ISSUE TITLE
Story "ssl_crime" in demo hangs if www.cloudflarechallenge.com not reachable

### ISSUE THREAD

**Issue by ncoelle** [continuumsecurity/bdd-security#10]
Hello,

when running `ant demo.run` behind our corporate web-proxy the site www.cloudflarechallenge.com is not reachable (which is not the issue here). I get several "java.net.ConnectException"s and "java.net.SocketException"s and then the ant command hangs. Here the last lines of the console:
 
    [java] (ssl.story)
     [java] Meta:
     [java] @story ssl
     [java]
     [java] Narrative:
     [java] In order to protect my data transmitted over the network
     [java] As a user
     [java] I want to verify that good SSL practices have been implemented and known weaknesses have been avoided
     [java]
     [java] Meta: @story ssl
     [java] Scenario: Disable SSL deflate compression in order to mitigate the risk of the CRIME attack
     [java] Meta:
     [java] @id ssl_crime
     [java]
     [java] could not connect to www.cloudflarechallenge.com/107.170.194.215:443: java.net.ConnectException: Operation timed out
     [java] could not connect to www.cloudflarechallenge.com/107.170.194.215:443: java.net.ConnectException: Operation timed out
     [java] could not connect to www.cloudflarechallenge.com/107.170.194.215:443: java.net.SocketException: Network is unreachable
     [java] could not connect to www.cloudflarechallenge.com/107.170.194.215:443: java.net.SocketException: Network is unreachable
     [java] No SSL/TLS server at www.cloudflarechallenge.com/107.170.194.215:443
     [java] could not connect to www.cloudflarechallenge.com/107.170.194.215:443: java.net.SocketException: Network is unreachable

After these lines nothing else happens (I let it run for 4h).

Environment:

    Mac OS 10.10
    java version "1.7.0_71"
    Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

and

    Mac OS 10.10
    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

and

    Windows 7 64Bit (German)
    java version "1.7.0_71"
    Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

**Comment by continuumsecurity** [comment]
Hi, thanks for reporting this.  The test suite can't connect to www.cloudflarechallenge.com because the SSL cert has been revoked.  I'll change this in the demo test to point to a different public server, but if you're running bdd-security on your own app, then you should point it to your own server.  
You can set the target in the config.xml file, in the "baseSecureUrl" tag:
E.g.:
<baseSecureUrl>https://www.wormly.com/</baseSecureUrl>

**Comment by continuumsecurity** [comment]
Default config.xml updated to use www.wormly.com for SSL tests.

**Comment by ncoelle** [comment]
Hello, 
thank you for your fast response.
Unfortunately your fix does not solve my problem. My problem is that `ant demo.run` hangs after the last line instead of logging an error and carrying on.

     [java] Meta: @story ssl
     [java] Scenario: Disable SSL deflate compression in order to mitigate the risk of the CRIME attack
     [java] Meta:
     [java] @id ssl_crime
     [java]
     [java] could not connect to www.wormly.com/107.22.240.62:443: java.net.SocketException: Network is unreachable
     [java] could not connect to www.wormly.com/107.22.240.62:443: java.net.ConnectException: Operation timed out
     [java] could not connect to www.wormly.com/107.22.240.62:443: java.net.ConnectException: Operation timed out
     [java] could not connect to www.wormly.com/107.22.240.62:443: java.net.ConnectException: Operation timed out
     [java] No SSL/TLS server at www.wormly.com/107.22.240.62:443
     [java] could not connect to www.wormly.com/107.22.240.62:443: java.net.ConnectException: Operation timed out

**Comment by continuumsecurity** [comment]
Ah. I misunderstood, will look into it.  In the meantime you can add a meta tag to the ssl story to skip it:
Meta: @story ssl @skip

**Comment by continuumsecurity** [comment]
The ssl tests now use the external program sslyze which is much faster than the previous method.  Download from https://github.com/nabla-c0d3/sslyze then configure the location in the config.xml
