### ISSUE TITLE
Adding a RunApp script

### ISSUE THREAD

**Issue by laminfaty** [continuumsecurity/bdd-security#13]
@continuumsecurity 
For our conversation few months ago, I came up with a script for scanning multiple stories at one time. However, we will need to tweak three main files: config.java, StoryRunnner.java, and BaseStoryRunner.java. I think i will be easier for you to make those changes because you built this framework. Please let me know your thoughts.

#!/bin/sh
export ANT_OPTS=-Xmx500m

#Exit when argument is less than 3
if [ $# -lt 3 ]
then
	echo "runApp <CustomConfig.xml> <LoginFlag> story1 story2 ...."
	exit
fi

cfg=$1
lfg=$2

numberOfStorie=`expr $# - 2`
echo "About to run $numberOfStorie stories with customConfig: $1 and LoginFlag: $2"

shift
shift
for str in "$@"
do
	echo "Running Story - $str with $cfg and Login $lfg"
	ant test -Dargs="$cfg $lfg -story $str"
		
done

**Comment by continuumsecurity** [comment]
Hi @laminfaty I've just committed changes that allow you to run parallel stories through Ant.  See the ant target junit.parallel
Be aware that any tests that use OWASP ZAP can't be run in parallel with other owasp zap tests, so these are all grouped together in one sequential run.  The example junit.parallel task runs 3 separate JVMs:
- browser based tests
- ssl and hostconfig
- nessus

**Comment by laminfaty** [comment]
@continuumsecurity 
Good Stuff!
I will test it tonight and see. It is no way people want to compare gaunlt with bed-security. I think this framework has a potential to be the best ever and the only way to get there is to improve it, make it easy ti use, and add new features.

**Comment by continuumsecurity** [comment]
@laminfaty :)
And thanks to your feedback, we can make it better.   
If there are other major features you'd like to see, or specific tools it should support please let me know.  You can create feature requests using this issue system.

**Comment by laminfaty** [comment]
@continuumsecurity 
We need to update the default ant command in build.xml. Also it be useful to document all latest ant commands.

**Comment by continuumsecurity** [comment]
Default command fixed.  Have started some documentation on the blog:
http://www.continuumsecurity.net/blog.html
