### ISSUE TITLE
AppScanningSteps Error

### ISSUE THREAD

**Issue by lfatty** [continuumsecurity/bdd-security#20]
@continuumsecurity, I got the following error when running the latest bed-sec.

test/src/main/java/net/continuumsecurity/steps/AppScanningSteps.java:92: error: cannot find symbol
byte[] xmlReport = scanner.getXmlReport();

**Comment by continuumsecurity** [comment]
Check that you have the latest version of lib/proxy-2.4-SNAPSHOT.jar

I've just clone the whole project from github into a clean directory and it works without error.

**Comment by lfatty** [comment]
@continuumsecurity I fixed the issue, however, I noted that the new scan policies you added today do not have CWEid in ZAP because those policies are not there by default.

**Comment by continuumsecurity** [comment]
Where the policy does not have a CWEId, I've also added the WASC-ID which are the only two external references ZAP uses.

**Comment by lfatty** [comment]
For instance HTTP Parameter polution and Expression Language injection are not in ZAP by default.

**Comment by continuumsecurity** [comment]
Thanks.  They were reported as being available through the API.  I've now removed them.
