### ISSUE TITLE
Update Zap proxy

### ISSUE THREAD

**Issue by lfatty** [continuumsecurity/bdd-security#26]
@continuumsecurity 

Is there any plan to update zap 2.4.0 to the latest greatest version 2.4.1 which took care many bugs?

**Comment by gabecase** [comment]
@continuumsecurity do we need any help with this? I plan to use this framework and am willing to contribute

**Comment by continuumsecurity** [comment]
Release was held up with this zaproxy issue: https://github.com/zaproxy/zaproxy/issues/1893
Will bundle a new build of zaproxy with bdd-security, but that means that if you use a downloaded version of zaproxy 2.4.2 it won't work with bdd-sec.

**Comment by continuumsecurity** [comment]
@gabecase if you'd like to help out I'm making the changes in the 2.4.2 branch of bdd-sec, so you're welcome to use clone that branch and pull down and compile the new build of zaproxy that corrects issue 1893

**Comment by gabecase** [comment]
alright that'd be cool
