### ISSUE TITLE
Issues with getting the authorisation feature to work 

### ISSUE THREAD

**Issue by streichsbaer** [continuumsecurity/bdd-security#50]
Hey Stephen, 

as you know, I've been taking a closer look at BDD-Security recently and am loving it.
After getting the authentication and some other features to work well, I've been playing around with the authorisation feature and have problems getting it to work.

A clip from the cucumber test pretty report looks like this.
<img width="962" alt="cucumber results_export" src="https://cloud.githubusercontent.com/assets/5006784/16706443/391749fe-45df-11e6-800a-f2d745a68ac7.png">

For some reason it skips 

```
14:22:02.159 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the login page STARTED
14:22:02.163 [DEBUG] [TestEventLogger] 
14:22:02.163 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the login page PASSED
14:22:02.168 [DEBUG] [TestEventLogger] 
14:22:02.168 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the username jack@metacorp.com STARTED
14:22:02.169 [DEBUG] [TestEventLogger] 
14:22:02.169 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the username jack@metacorp.com SKIPPED
14:22:02.171 [DEBUG] [TestEventLogger] 
14:22:02.171 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the password yankeessuck STARTED
14:22:02.176 [DEBUG] [TestEventLogger] 
14:22:02.176 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.And the password yankeessuck SKIPPED
14:22:02.180 [DEBUG] [TestEventLogger] 
14:22:02.180 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.When the user logs in STARTED
14:22:02.181 [DEBUG] [TestEventLogger] 
14:22:02.181 [DEBUG] [TestEventLogger] net.continuumsecurity.junit.SecurityTest > | viewJacksInfo | jack@metacorp.com | yankeessuck | Jack Mannin |.When the user logs in SKIPPED
```

The authorisation.feature file can be seen below. I'm testing BDD-Security on RailsGoat currently.
[authorisation.feature.feature.txt](https://github.com/continuumsecurity/bdd-security/files/355429/authorisation.feature.feature.txt)

Finally, my current RailsGoatApplication.java file is attached below:
[RailsGoatApplication.java.txt](https://github.com/continuumsecurity/bdd-security/files/355435/RailsGoatApplication.java.txt)

Looking at the line And the username <username> it doesn't seem to have an according WebApplicationSteps.java mapping. There is one for @Given but not for @And. I've even tried mix and matching the keywords, but without success.

```
@Given("^the username (\\s+)$")
    public void setUsernameFromExamples(String username) {
        World.getInstance().getUserPassCredentials().setUsername(username);
    }
```

Any idea what needs to be done to make it work?

Thanks,
Stefan

**Comment by streichsbaer** [comment]
FYI, I ran the default authorisation feature of bdd-security config against ropeytasks.jar and have similar results as mentioned above.

<img width="980" alt="bdd-security-vs-ropeytasks_authorisation" src="https://cloud.githubusercontent.com/assets/5006784/16706780/a950e6ce-45eb-11e6-974a-5962447dbb4a.png">

**Comment by continuumsecurity** [comment]
Thanks @streichsbaer I've reproduced the same error in RopeyTasks.  Investigating now.

**Comment by continuumsecurity** [comment]
Was a regex problem, fixed with:
`    @Given("^the username (.*)$")`

and:

`    @Given("^the password (.*)$")`

Have tested it with RopeyTasks, let me know whether it works for RailsGoat.

**Comment by streichsbaer** [comment]
Thanks for the fast response. I was wondering about the regex, but because it seemed to show up correctly in the steps I thought it's alright. I'm going to test once I am back home.

**Comment by streichsbaer** [comment]
Excellent, all working now! Thank you.

<img width="1043" alt="railsgoat_overview" src="https://cloud.githubusercontent.com/assets/5006784/16712205/4dc392bc-46b2-11e6-90ad-7400128cec96.png">

<img width="968" alt="railsgoat_authorisation" src="https://cloud.githubusercontent.com/assets/5006784/16712207/5747fed6-46b2-11e6-9f5d-3e46d6662622.png">

**Comment by continuumsecurity** [comment]
Great to hear!  New feature requests/pull requests welcome :)
