### ISSUE TITLE
Error: Invalid or corrupt jarfile ropeytasks.jar

### ISSUE THREAD

**Issue by jnogol** [continuumsecurity/bdd-security#64]
Trying to follow the Getting started guid, I stumbled upon this error. I have jdk8 in my computer, but tried anyway with a Docker container with openjkd8 and neither worked. Can you please check if the jar is correct? 

Thanks in advance

**Comment by santapau** [comment]
Hi, 

Just tested the ropeytasks.jar file you can get from here (https://github.com/continuumsecurity/RopeyTasks/blob/master/ropeytasks.jar) and it is working for us.

You can check it has correctly been downloaded. The sha1 for the working file is: e0f60ae15931c0e213e3446c9a72d574d7493b27

**Comment by jnogol** [comment]
Weird, if I download the file using curl or wget I get several sha1 hashes, but if I download it via web browser it works perfectly and the hash is the one you mentioned. Guess it is not an issue on your side, so this one should be closed. My apologies for the inconveniences.
