### ISSUE TITLE
java.lang.NullPointerException** when doing nessus scan

### ISSUE THREAD

**Issue by mike123vn** [continuumsecurity/bdd-security#71]
I cannot do nessus scan even i setup nessus server successfuly 
Bdd security Version 2.1
Nessus Version:  6.10.5
OS: MAC OS
> @nessus_scan
> Feature: Nessus Scan
> Scan the hosts for known security vulnerabilities
> Scenario: The host systems should not expose known security vulnerabilities
> Given a nessus API client that accepts all hostnames in SSL certificates110ms
> And a nessus version 6 server at https://localhost:8834360ms
> And the scanning policy named bdd-policy000ms
> And the target host names001ms
> canhme.com
> **When the scanner is run with scan name bddscan02s 444ms
> java.lang.NullPointerException**
> at net.continuumsecurity.v6.ScanClientV6.getPolicyV6ByName(ScanClientV6.java:41)
> at net.continuumsecurity.v6.ScanClientV6.newScan(ScanClientV6.java:65)
> at net.continuumsecurity.steps.NessusScanningSteps.runScan(NessusScanningSteps.java:67)
> at ✽.When the scanner is run with scan name bddscan(nessus_scan.feature:11)
> And the list of issues is stored000ms
> And the following nessus false positive are removed000ms
> pluginId	hostname
>

**Comment by stephendv1** [comment]
Could you check 2 things on the nessus server:
1. Does a policy named "bdd-policy" exist?
2. After getting this exception does a scan with the name "bddscan" exist on the nessus server?

**Comment by mike123vn** [comment]
Thank you for your support. I haven't created bdd-security policy.
